use amelinium;
--;;
ALTER TABLE user_settings DROP FOREIGN KEY IF EXISTS FK_user_settings_user_id_users;
--;;
ALTER TABLE users DROP FOREIGN KEY IF EXISTS FK_created_by_id_users;
--;;
ALTER TABLE users DROP FOREIGN KEY IF EXISTS FK_password_suites_id_password_suite;
--;;
ALTER TABLE session_variables DROP FOREIGN KEY IF EXISTS FK_session_id_sessions;
--;;
ALTER TABLE sessions DROP FOREIGN KEY IF EXISTS FK_sessions_user_id_users;
--;;
ALTER TABLE sessions DROP FOREIGN KEY IF EXISTS FK_sessions_user_email_users;
--;;
ALTER TABLE roles DROP FOREIGN KEY IF EXISTS FK_roles_user_id_users;
--;;
DROP INDEX IF EXISTS role_index ON roles;
--;;
DROP INDEX IF EXISTS account_type_index ON users;
--;;
DROP INDEX IF EXISTS uid ON users;
--;;
DROP INDEX IF EXISTS user_id ON sessions;
--;;
DROP INDEX IF EXISTS authlog_operation_index ON authlog;
--;;
DROP INDEX IF EXISTS authlog_level_index ON authlog;
--;;
DROP INDEX IF EXISTS authlog_client_index ON authlog;
--;;
DROP INDEX IF EXISTS authlog_user_id_index ON authlog;
--;;
DROP INDEX IF EXISTS authlog_success_index ON authlog;
--;;
DROP INDEX IF EXISTS session_variables_index ON session_variables;
--;;
DROP INDEX IF EXISTS user_settings_index ON user_settings;
--;;
DROP TABLE IF EXISTS authlog;
--;;
DROP TABLE IF EXISTS user_settings;
--;;
DROP TABLE IF EXISTS session_variables;
--;;
DROP TABLE IF EXISTS sessions;
--;;
DROP TABLE IF EXISTS users;
--;;
DROP TABLE IF EXISTS roles;
--;;
DROP TABLE IF EXISTS users;
--;;
DROP TABLE IF EXISTS password_suites;
